defmodule Tauper.Games.Tables.EducemFar do
  @name "Taula Periòdica Educem FAR (català)"
  @elements %{
    1 => %{symbol: "H", name: "Hidrogen", valences: [1], group: 1},
    2 => %{symbol: "He", name: "Heli", valences: [0], group: 18},
    3 => %{symbol: "Li", name: "Liti", valences: [1], group: 1},
    4 => %{symbol: "Be", name: "Beril·li", valences: [2], group: 2},
    5 => %{symbol: "B", name: "Bor", valences: [3], group: 13},
    6 => %{symbol: "C", name: "Carboni", valences: [2, 4], group: 14},
    7 => %{symbol: "N", name: "Nitrogen", valences: [3, 5], group: 15},
    8 => %{symbol: "O", name: "Oxigen", valences: [2], group: 16},
    9 => %{symbol: "F", name: "Fluor", valences: [1], group: 17},
    10 => %{symbol: "Ne", name: "Neó", valences: [0], group: 18},
    11 => %{symbol: "Na", name: "Sodi", valences: [1], group: 1},
    12 => %{symbol: "Mg", name: "Magnesi", valences: [2], group: 2},
    13 => %{symbol: "Al", name: "Alumini", valences: [3], group: 13},
    14 => %{symbol: "Si", name: "Silici", valences: [4], group: 14},
    15 => %{symbol: "P", name: "Fòsfor", valences: [3, 5], group: 15},
    16 => %{symbol: "S", name: "Sofre", valences: [2, 4, 6], group: 16},
    17 => %{symbol: "Cl", name: "Clor", valences: [1, 3, 5, 7], group: 17},
    18 => %{symbol: "Ar", name: "Argó", valences: [0], group: 18},
    19 => %{symbol: "K", name: "Potassi", valences: [1], group: 1},
    20 => %{symbol: "Ca", name: "Calci", valences: [2], group: 2},
    25 => %{symbol: "Mn", name: "Manganès", valences: [2, 3, 4, 6, 7], group: 7},
    26 => %{symbol: "Fe", name: "Ferro", valences: [2, 3], group: 8},
    27 => %{symbol: "Co", name: "Cobalt", valences: [2, 3], group: 9},
    28 => %{symbol: "Ni", name: "Niquel", valences: [2, 3], group: 10},
    29 => %{symbol: "Cu", name: "Coure", valences: [1, 2], group: 11},
    30 => %{symbol: "Zn", name: "Zinc", valences: [2], group: 12},
    31 => %{symbol: "Ga", name: "Gal·li", valences: [3], group: 13},
    32 => %{symbol: "Ge", name: "Germani", valences: [2, 4], group: 14},
    33 => %{symbol: "As", name: "Arsènic", valences: [3, 5], group: 15},
    34 => %{symbol: "Se", name: "Seleni", valences: [2, 4, 6], group: 16},
    35 => %{symbol: "Br", name: "Brom", valences: [1, 3, 5, 7], group: 17},
    36 => %{symbol: "Kr", name: "Criptó", valences: [0], group: 18},
    37 => %{symbol: "Rb", name: "Rubidi", valences: [1], group: 1},
    38 => %{symbol: "Sr", name: "Estronci", valences: [2], group: 2},
    47 => %{symbol: "Ag", name: "Argent", valences: [1], group: 11},
    48 => %{symbol: "Cd", name: "Cadmi", valences: [2], group: 12},
    49 => %{symbol: "In", name: "Indi", valences: [3], group: 13},
    50 => %{symbol: "Sn", name: "Estany", valences: [2, 4], group: 14},
    51 => %{symbol: "Sb", name: "Antimoni", valences: [3, 5], group: 15},
    52 => %{symbol: "Te", name: "Tel·luri", valences: [2, 4, 6], group: 16},
    53 => %{symbol: "I", name: "Iode", valences: [1, 3, 5, 7], group: 17},
    54 => %{symbol: "Xe", name: "Xenó", valences: [0], group: 18},
    55 => %{symbol: "Cs", name: "Cesi", valences: [1], group: 1},
    56 => %{symbol: "Ba", name: "Bari", valences: [2], group: 2},
    79 => %{symbol: "Au", name: "Or", valences: [1, 3], group: 11},
    80 => %{symbol: "Hg", name: "Mercuri", valences: [1, 2, 4], group: 12},
    81 => %{symbol: "Tl", name: "Tal·li", valences: [1, 3], group: 13},
    82 => %{symbol: "Pb", name: "Plom", valences: [2, 4], group: 14},
    83 => %{symbol: "Bi", name: "Bismut", valences: [3, 5], group: 15},
    84 => %{symbol: "Po", name: "Poloni", valences: [2, 4], group: 16},
    85 => %{symbol: "At", name: "Àstat", valences: [2, 3], group: 17},
    86 => %{symbol: "Rn", name: "Radó", valences: [0], group: 18},
    87 => %{symbol: "Fr", name: "Franci", valences: [1], group: 1},
    88 => %{symbol: "Ra", name: "Radi", valences: [2], group: 2}
  }

  def elements, do: @elements

  def name, do: @name
end
